name: 10-dim-of-op-change1

dependencies:
  - jupyter=1.0
  - python=3.8
  - gensim=4.0.1
  - matplotlib=3.3.4
  - nltk=3.7
  - numpy=1.24.4
  - pandas=1.2.3
  - scikit-learn=0.24
  - seaborn=0.11
  - statsmodels=0.13.5
  - spacy=2.3.2
  - tqdm=4.59
